# Generated by Django 4.1.3 on 2025-05-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='bio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='uid',
            field=models.CharField(max_length=255),
        ),
    ]
